# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks


#altered to run use system (current conda env) as pyhton installs blaocked by it
repos:
  - repo: local
    hooks:
      - id: nbstripout
        name: nbstripout
        entry: nbstripout
        language: system
        types: [jupyter]
        args: [ --extra-keys, "metadata.colab metadata.kernelspec cell.metadata.colab cell.metadata.executionInfo cell.metadata.id cell.metadata.outputId"]
        require_serial: true

      - id: isort
        name: isort Sort python imports (auto-fixes)
        entry: isort
        require_serial: true
        language: system
        types_or: [python]
        args: [ "--profile", "black", "--filter-files" ]
      
      - id: isort
        name: isort Sort cython imports (auto-fixes)
        entry: isort
        require_serial: true
        language: system
        types_or: [cython]
        args: [ "--profile", "black", "--filter-files" ]

      - id: isort
        name: isort Sort pyi imports (auto-fixes)
        entry: isort
        require_serial: true
        language: system
        types_or: [pyi]
        args: [ "--profile", "black", "--filter-files" ]

      - id: ruff-check
        name: ruff check
        description: "Run 'ruff check' for extremely fast Python linting"
        entry: ruff check --force-exclude
        language: system
        types_or: [python, pyi, jupyter]
        args: [ --fix ]
        require_serial: true
        additional_dependencies: []
        minimum_pre_commit_version: "2.9.2"

      - id: ruff-format
        name: ruff format
        description: "Run 'ruff format' for extremely fast Python formatting"
        entry: ruff format --force-exclude
        language: system
        types_or: [python, pyi, jupyter]
        args: []
        require_serial: true
        additional_dependencies: []
        minimum_pre_commit_version: "2.9.2"

      - id: detect-secrets
        name: Detect secrets
        description: Detects high entropy strings that are likely to be passwords.
        entry: detect-secrets-hook
        language: system

      - id: bandit
        name: bandit
        args: ["-c", "pyproject.toml"]
        description: 'Bandit is a tool for finding common security issues in Python code'
        entry: bandit
        language: system
        types: [python]
        require_serial: true
  