[mypy]
python_version = 3.12
mypy_path = ./typings
disallow_untyped_defs = True
warn_return_any = True
explicit_package_bases = True
strict_optional = True

[mypy-dhsc_data_tools.*]
ignore_missing_imports = True
