[project]
name = "dhsc_data_tools"
version = "0.0.1"
authors = [
  { name="Data Science Hub", email="datascience@dhsc.gov.uk" },
]
description = "An internal Python package to facilitate working with the DAC"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.8"
dependencies = [
  "os",
  "pyodbc",
  "pypac",
  "azure-identity",
  "azure-keyvault-secrets",
  "databricks-connect",
  "configparser",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Cloud Computing :: Microsoft Azure :: Azure Databricks",
    "Private :: Do Not Upload",
]

[project.urls]
Homepage = "https://github.com/DataS-DHSC/dhsc-data-tools"
Issues = "https://github.com/DataS-DHSC/dhsc-data-tools/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"