[project]
name = "DHSCdataPy"
version = "0.0.1"
authors = [
  { name="Richard Pordan", email="richard.pordan@dhsc.gov.uk" },
]
description = "An internal Python package to facilitate working with the DAC"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Cloud Computing :: Microsoft Azure :: Azure Databricks"
]

[project.urls]
Homepage = "https://github.com/DataS-DHSC/DHSCdataPy"
Issues = "https://github.com/DataS-DHSC/DHSCdataPy/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"