# Adapted from https://github.com/mkleehammer/pyodbc
# ignore line spacing (E303), mixed case names (N802/N803)
from collections.abc import Generator, Iterator, Sequence
from typing import Any, Self

class Connection:
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type, exc_value, traceback) -> None:  # type: ignore
        ...
    def cursor(self) -> Cursor: ...
    def execute(self, sql: str, *params: Any) -> Cursor: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...

class Cursor:
    @property
    def connection(self) -> Connection: ...
    @property
    def description(
        self,
    ) -> tuple[tuple[str, Any, int, int, int, int, bool]]: ...
    # implemented dunder methods
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type, exc_value, traceback) -> None:  # type: ignore
        ...
    def __iter__(self, /) -> Cursor: ...
    def __next__(self, /) -> Row: ...
    def execute(self, sql: str, *params: Any) -> Cursor: ...
    def executemany(
        self,
        sql: str,
        params: Sequence | Iterator | Generator,
        /,
    ) -> None: ...
    def fetchone(self) -> Row | None: ...
    def fetchmany(self, size: int, /) -> list[Row]: ...
    def fetchall(self) -> list[Row]: ...
    def fetchval(self) -> Any: ...
    def skip(self, count: int, /) -> None: ...
    def nextset(self) -> bool: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def cancel(self) -> None: ...
    def close(self) -> None: ...

class Row:
    @property
    def cursor_description(
        self,
    ) -> tuple[tuple[str, Any, int, int, int, int, bool]]: ...
    def __iter__(self) -> Any: ...

def connect(
    connstring: str | None = None,
    /,
    *,
    autocommit: bool = False,
    encoding: str = "utf-16le",
    readonly: bool = False,
    timeout: int = 0,
    attrs_before: dict[int, int | bytes | bytearray | str | Sequence[str]]
    | None = None,
    **kwargs: Any,
) -> Connection: ...
