name: QA and Security Scan

on:
  pull_request:
  push:
    branches:
      - main
      - canary

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:

  qa:
    name: Code QA Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install uv and Set Python Version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
          cache-dependency-glob: ""

      - name: Install Project Dependencies
        run: |
          uv sync --extra dev --extra docs

      - name: Run Ruff Linter
        run: uv run ruff check .

      - name: Run MyPy Type Check
        run: uv run mypy dhsc_data_tools

  security:
    name: Code and Dependency Security Scan
    uses: dhsc-govuk-internal/github-python-workflows/.github/workflows/security.yml@2128989cb1015ceec6d8c88e6f7275f7cff28351
    with:
      python_version: "3.12"
