name: QA

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-and-qa:
    name: Lint & QA Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install uv and Set Python Version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
          cache-dependency-glob: ""

      - name: Install Project Dependencies
        run: |
          uv sync --group dev --group docs

      - name: Run Ruff Linter
        run: uv run ruff check

      - name: Run MyPy Type Check
        run: uv run mypy .
